### ISSUE TITLE
should there be a separate purge room command?

### ISSUE THREAD

**Issue by jjj333-p** [jjj333-p/dendrite-admin-interface#10]
Okay so i've already created an evacuateRoom endpoint which evacuates the room and then purges it from the db (unless supplied with the preserve flag). I know the purgeroom endpoint had to be separated from the evacuateRoom endpoint because it caused issues. should  this added as an independent command to just purge it from the db? because of the way the http endpoints work the interface will still run the purgeRoom endpoint even dendrite is unable to successfully evacuate the room so in theory that same issue is not a concern.

**Comment by TruncatedDinoSour** [comment]
i think u should sep it bc its sorta weird w the flag

**Comment by jjj333-p** [comment]
damn and i had just became confident in my decision to use the flag.

my thinking is mainly that it can cause issues to purge without evacuating and very rarely would anyone want to evacuate and not to purge it

**Comment by TruncatedDinoSour** [comment]
> my thinking is mainly that it can cause issues to purge without evacuating and very rarely would anyone want to evacuate and not to purge it

i think it adds unnecessary confusion personally, i think ( esp for matrix bots, which dont have a standard flag interface and client autocompletion  ) its better to jusr leave them simple on a `!command argument` basis rather than adding flags, which can cause confusion and annoyance

**Comment by jjj333-p** [comment]
> ( esp for matrix bots, which dont have a standard flag interface and client autocompletion ) 

i mean i was copying the style common with bash which doesnt have a "standard flag interface" afaik, and definitely no autocompletion. 

mainly because i cant see it being very common to ever run it with the flag

perhaps it could be an argument of the command?

**Comment by TruncatedDinoSour** [comment]
> > ( esp for matrix bots, which dont have a standard flag interface and client autocompletion )
> 
> i mean i was copying the style common with bash which doesnt have a "standard flag interface" afaik, and definitely no autocompletion.
> 
> mainly because i cant see it being very common to ever run it with the flag
> 
> perhaps it could be an argument of the command?

no shell rlly has a std flag interface, but a lot of shells ( yes, including bash ) have autocompletion, but idk, imo itd b best to seperate `purge` and `evacuate` into diff commands, at least by my view with current matrix protocol capabilities itd b best to keep it simple rather than w flags xD

**Comment by jjj333-p** [comment]
but those are things generally meant to be ran together which means its harder for the most common action and someone who might not know to do both could do a less optimal thing by accident. and

**Comment by TruncatedDinoSour** [comment]
> but those are things generally meant to be ran together which means its harder for the most common action and someone who might not know to do both could do a less optimal thing by accident. and

ag
